apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wbfk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wbfk
    app.kubernetes.io/part-of: tkrw-pr714-0075-0062-app
  name: devfile-sample-wbfk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wbfk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wbfk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0062-tenant/tkrw-pr714-0075-0062-app/devfile-sample-wbfk@sha256:2210f7702b829c6f29e5a2b20b3a3f9f5447bc66dd0e6ade56dcb9db7837d44f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
